tunnel:
  enabled: true
  type: "cloudflare"  # cloudflare, port_forward (legacy)
  
  cloudflare:
    enabled: true
    hostname: "slovak-conflict-antibody-specialists.trycloudflare.com"
    local_port: 8082
    protocol: "quic"
    auto_start: true
    
  port_forward:
    enabled: false  # Disabled due to firewall/NAT issues
    port_range_start: 8080
    port_range_end: 9000
    enable_dns_proxy: false

security:
  require_authentication: true
  allowed_origins: ["*"]
  rate_limit: 100  # requests per minute
  timeout: 30s

logging:
  level: "info"
  enable_request_logging: true
  enable_error_logging: true 